name: Terraform EKS Workflow with (OIDC) 

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Apply or Destroy Terraform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      confirmation:
        description: "Type 'CONFIRM' to proceed with destruction (required for destroy)"
        required: false
        default: ""

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.7.0
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Enables OIDC authentication
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/aws_eks_oidc_connectivity
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory: terraform-eks/

    - name: Check Destroy Confirmation
      if: github.event.inputs.action == 'destroy'
      run: |
        if [[ "${{ github.event.inputs.confirmation }}" != "CONFIRM" ]]; then
          echo "Destruction confirmation not provided or incorrect. Exiting."
          exit 1
        fi

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve
      working-directory: terraform-eks/

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy' && github.event.inputs.confirmation == 'CONFIRM'
      run: terraform destroy -auto-approve
      working-directory: terraform-eks/

    
    # Optional: Add steps to store tfstate remotely (S3 for AWS) if not already configured in your .tf files
    - name: Upload Terraform State (if not using remote backend)
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state
        path: terraform/terraform.tfstate
      if: always() # Always upload, even if previous steps fail
